//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EromasovKursach.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazchik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakazchik()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int ZakazchikId { get; set; }
        public string ZakazchikName { get; set; }
        public string ZakazchikAdress { get; set; }
        public int ZakazchikRaschetniyShet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
