//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EromasovKursach.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int ZakazId { get; set; }
        public int ZakazchikId { get; set; }
        public int TovarId { get; set; }
        public int Count { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Zakazchik Zakazchik { get; set; }
    }
}
